Program.exe: Daisyworld.cs Patch.cs Livingthing.cs Program.cs
	gmcs Program.cs Daisyworld.cs Patch.cs Livingthing.cs
Program2.exe: Daisyworld.cs Patch.cs Livingthing.cs Program2.cs
	gmcs Program2.cs Daisyworld.cs Patch.cs Livingthing.cs
